version: '3.4'

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=app
      - MONGODB_APPLICATION_USER=app
      - MONGODB_APPLICATION_PASS=app

  app:
      build: .
      ports:
        - "5000:5000"
      depends_on:
        - mongodb
      volumes:
        - .:/usr/src/app
        - /etc/localtime:/etc/localtime:ro
      working_dir: "/usr/src/app"
      restart: on-failure:5
      env_file:
        - .env
      environment:
        - LANG=C.UTF-8
        - FLASK_APP=run.py
        - APP_ENVIRONMENT=development
        - APP_DOMAIN=${APP_DOMAIN}
        - APP_ADMIN=admin@${APP_DOMAIN}
        - APP_FROM=no-reply@${APP_DOMAIN}
        - API_KEY=${API_KEY}
        - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
        - MAILGUN_API=${MAILGUN_API}
